server:
  port: 8899
      
---
  
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/testjpa?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: oneinvest
    password: oneinvest123
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update

---
  
spring:
  config:
    activate:
      on-profile: test

---

spring:
  config:
    activate:
      on-profile: prod
